### ISSUE TITLE
API: Enable partner engineers to set certification on collections

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy-dev#132]
-   update the set certified viewset to be able to update a collection's certification to `certified` or `not_certified` and update this to use the new pulp certification endpoint (https://pulp.plan.io/issues/5579)
    - This endpoint should go under `v3/` instead of `v3/_ui`
    -   this endpoint should return a permission denied error if the user is not part of the partner engineer group
-   update the  endpoint to `v3/_ui/collections/`
    -   query pulp with `certificaton=certified` by default
    -   on the detail view (`v3/_ui/collections/{namespace}/{collection`), ensure that only `certified` versions are returned in `all_versions`
    -   add `certification` to the returned list of fields

**Comment by romanblanco** [comment]
https://github.com/pulp/pulp_ansible/pull/237

**Comment by romanblanco** [comment]
part of the issue addressed in https://github.com/ansible/galaxy-api/pull/106

**Comment by alikins** [comment]
Wondering if the '_ui/' views should be mostly "read-only" since they are composite / aggregations.  For ex, I wouldn't expect to be able to create a Collection and multiple CollectionVersions by POST /api/automation-hub/v3/_ui/collections/.

The alternative would be do updates and creates directly to the canonical resource. For example, updating a CollectionVersion to be 'certified' would be a `PUT /api/automation-hub/v3/collections/{namespace}/{name}/versions/{version}/certified`. That would match the pulp_ansible API.

Similarly, for 'deprecated', updating deprecated status would be a `PUT  /api/automation-hub/v3/collections/{namespace}/{name}/`.  This also matches the pulp_ansible API.

**Comment by romanblanco** [comment]
working on this in [romanblanco:issue132](https://github.com/ansible/galaxy-api/compare/master...romanblanco:issue132) branch

**Comment by romanblanco** [comment]
> This endpoint should go under v3/ instead of v3/_ui

update: the endpoint should stay
