### ISSUE TITLE
On namespace edit page, UI progress indicators get "stuck" after saving changes

### ISSUE THREAD

**Issue by alikins** [ansible/galaxy-dev#252]
On ci, if I go to the ui and edit namespace stuff, the ui seems to get stuck showing progress indicators.

aka changing something at this url and saving it:
   https://ci.cloud.redhat.com/ansible/automation-hub/my-namespaces/edit/alikins_test_ns

Also seen on https://ci.cloud.redhat.com/ansible/automation-hub/my-namespaces/edit/blippy?tab=edit%20resources 

![ci cloud namespace_edit_spinning](https://user-images.githubusercontent.com/15162/74043369-3ec1d080-4997-11ea-8e41-c0d21d5639a2.png)

**Comment by romanblanco** [comment]
@alikins trying to click around https://ci.cloud.redhat.com/ansible/automation-hub/my-namespaces/alikins_test_ns, I'm not hitting any issues:

![Screencast from 2020-02-10 09-52-44](https://user-images.githubusercontent.com/1187051/74139248-f26ece80-4bea-11ea-9e0c-baf4a2b122b2.gif)

Is the issue still reproducible?

**Comment by newswangerd** [comment]
@romanblanco I can't point you to the broken namespace on the CI environment because it's broken for me, but if you create a namespace with invalid data it doesn't show any error messages and the API response is blank.

![Screen Recording 2020-02-10 at 9 42 18 AM mov](https://user-images.githubusercontent.com/6063371/74159446-d0288100-4be9-11ea-975b-1d386fd7b7e4.gif)

**Comment by romanblanco** [comment]
@newswangerd what reported @alikins seems to be an issue on the edit page, not in the modal. If the problem is in the modal, this issue is a duplicity of https://github.com/ansible/galaxy-dev/issues/253#issue-561867562
